import React, { useState } from 'react';
import { ActivityIndicator, Modal, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useAppTheme } from '../../../theme/ThemeContext';

export default function CreatePollModal({ visible, onClose, onCreate }: { visible: boolean; onClose: () => void; onCreate: (question: string, options: string[]) => Promise<void> }) {
  const { theme } = useAppTheme(); const [question, setQuestion] = useState(''); const [options, setOptions] = useState(['', '']); const [saving, setSaving] = useState(false);
  const submit = async () => { const clean = options.map(v => v.trim()).filter(Boolean); if (!question.trim() || clean.length < 2) return; setSaving(true); try { await onCreate(question.trim(), clean); setQuestion(''); setOptions(['', '']); onClose(); } finally { setSaving(false); } };
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.overlay}><View style={[styles.card, { backgroundColor: theme.card }]}><Text style={[styles.title, { color: theme.text }]}>Create poll</Text><TextInput value={question} onChangeText={setQuestion} placeholder="Ask a question" placeholderTextColor={theme.secondaryText} style={[styles.input, { color: theme.text, borderColor: theme.border }]} />{options.map((value, index) => <TextInput key={index} value={value} onChangeText={next => setOptions(current => current.map((item, i) => i === index ? next : item))} placeholder={`Option ${index + 1}`} placeholderTextColor={theme.secondaryText} style={[styles.input, { color: theme.text, borderColor: theme.border }]} />)}{options.length < 10 ? <TouchableOpacity onPress={() => setOptions(current => [...current, ''])}><Text style={[styles.add, { color: theme.primary }]}>+ Add option</Text></TouchableOpacity> : null}<View style={styles.actions}><TouchableOpacity onPress={onClose} style={styles.action}><Text style={{ color: theme.secondaryText }}>Cancel</Text></TouchableOpacity><TouchableOpacity onPress={submit} disabled={saving} style={[styles.create, { backgroundColor: theme.primary }]}>{saving ? <ActivityIndicator color="#FFF" /> : <Text style={styles.createText}>Create</Text>}</TouchableOpacity></View></View></View></Modal>;
}
const styles = StyleSheet.create({ overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,.5)', justifyContent: 'center', padding: 22 }, card: { borderRadius: 22, padding: 20 }, title: { fontSize: 20, fontWeight: '800', marginBottom: 15 }, input: { height: 46, borderWidth: 1, borderRadius: 12, paddingHorizontal: 12, marginBottom: 10 }, add: { fontWeight: '700', marginVertical: 7 }, actions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 12 }, action: { padding: 12 }, create: { minWidth: 86, height: 43, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, createText: { color: '#FFF', fontWeight: '800' } });
